server.port=8013

# ========================
# DATABASE CONFIG
# ========================
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://mysql-db:3306/authdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.username=root
db.password=root

spring.application.name=login

# ========================
# HIBERNATE CONFIG
# ========================
hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update

# ========================
# ENTITY PACKAGE
# ========================
entitymanager.packagesToScan=com

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka