server.port=1690
spring.application.name=interview-service

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true

# MYSQL
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://mysql-db:3306/interviewdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.username=root
db.password=root

# HIBERNATE
hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update


entitymanager.packagesToScan=com
