server.port=8010
spring.application.name=OrderService

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.client.registry-fetch-interval-seconds=5
management.endpoints.web.exposure.include=health,info

# =====================
# MYSQL CONFIG
# =====================
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://mysql-db:3306/orderdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.username=root
db.password=root

# =====================
# HIBERNATE CONFIG
# =====================
hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update

entitymanager.packagesToScan=com

spring.cloud.openfeign.circuitbreaker.enabled=true